
CREATE TABLE EMPLOYEES(
    ID NUMBER(*,0) NOT NULL, 
    MANAGER_ID NUMBER(*,0), 
    DATE_OF_JOINING DATE, 
    FULL_NAME VARCHAR(255) NOT NULL,    
    CONSTRAINT EMPLOYEES_PK PRIMARY KEY (ID)
    
);
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID);   


 CREATE TABLE SALARIES(
    ID NUMBER(*,0) NOT NULL, 
    EMPLOYEE_ID NUMBER(*,0) NOT NULL, 
    PROJECT_ID NUMBER(*,0), 
    SALARY NUMBER(10,2) NOT NULL CHECK (SALARY>500),
    CONSTRAINT SALARIES_PK PRIMARY KEY (ID),
    CONSTRAINT FK_SALARY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID),
    CONSTRAINT FK_SALARY_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID)
);
  
    
    CREATE TABLE PROJECTS(
    ID NUMBER(*,0) NOT NULL, 
    CODE VARCHAR(255) NOT NULL, 
    MANAGER_ID NUMBER(*,0) NOT NULL, 
    BUDGET NUMBER(10,2) NOT NULL,
    DATE_OF_BEGINNING DATE, 
    DATE_OF_ENDING DATE, 
    CONSTRAINT PROJECTS_PK PRIMARY KEY (ID),
    CONSTRAINT FK_MANAGER_PROJECT FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID)
);


CREATE TABLE EMPLOYEES(
    ID NUMBER(*,0) NOT NULL, 
    MANAGER_ID NUMBER(*,0), 
    DATE_OF_JOINING DATE, 
    FULL_NAME VARCHAR(255) NOT NULL,    
    CONSTRAINT EMPLOYEES_PK PRIMARY KEY (ID)
    
);
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID);